name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-2
# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ env.matrix }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set Matrix
        id: set-matrix
        run: |
          # Detect the changed directories among auth, converter, gateway, and notification
          changed_dirs=$(git diff --dirstat=files,0 HEAD~1..HEAD -- ./src/auth ./src/converter ./src/gateway ./src/notification | awk '{print $2}' | xargs -n1 basename | jq -R . | jq -cs .)
          echo "matrix=${changed_dirs}" >> $GITHUB_ENV

  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.SANDBOX_AWS_ACCOUNT_ID }}:role/GithubActionsRole
          role-session-name: GithubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src/${{ fromJSON(env.matrix)[0].dir }}
          push: false
          tags: ${{ secrets.SANDBOX_AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ fromJSON(env.matrix)[0].dir }}:${{ fromJSON(env.matrix)[0].dir }}-${{ github.sha }}

      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src/${{ fromJSON(env.matrix)[0].dir }}
          push: true
          tags: ${{ secrets.SANDBOX_AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ fromJSON(env.matrix)[0].dir }}:${{ fromJSON(env.matrix)[0].dir }}-${{ github.sha }}
