name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-2
# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set Matrix
        id: set-matrix
        run: |
          # Detect the changed directories among auth, converter, gateway, and notification
          changed_dirs=$(git diff --dirstat=files,0 HEAD~1..HEAD -- ./src/auth ./src/converter ./src/gateway ./src/notification | awk '{print $2}' | xargs -n1 basename | jq -R . | jq -cs .)
          echo "::set-output name=matrix::${changed_dirs}"

  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: ${{ secrets.SANDBOX_GITHUB_ACTION_AWS_ROLE_ARN }}
          role-session-name: GithubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src/${{ fromJSON(needs.prepare.outputs.matrix)[0].dir }}
          push: true
          tags: <account-id>.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/<image-name>:${{ fromJSON(needs.prepare.outputs.matrix)[0].dir }}-${{ github.sha }}