name: sandbox-ecr-build-and-push

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**/Dockerfile'
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.SANDBOX_AWS_ACCOUNT_ID }}:role/GithubActionsRole
          role-session-name: GithubActionsRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push auth service Docker image
        id: build-auth
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t "$ECR_REGISTRY"/cloudsbits-audiotube-sandbox:auth-"$IMAGE_TAG" -f src/auth/Dockerfile src/auth
          docker push "$ECR_REGISTRY"/cloudsbits-audiotube-sandbox:auth-"$IMAGE_TAG"

      - name: Build and push converter service Docker image
        id: build-converter
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t "$ECR_REGISTRY"/cloudsbits-audiotube-sandbox:converter-"$IMAGE_TAG" -f src/converter/Dockerfile src/converter
          docker push "$ECR_REGISTRY"/cloudsbits-audiotube-sandbox:converter-"$IMAGE_TAG"
        
      - name: Build and push gateway service Docker image
        id: build-gateway
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t "$ECR_REGISTRY"/cloudsbits-audiotube-sandbox:gateway-"$IMAGE_TAG" -f src/gateway/Dockerfile src/gateway
          docker push "$ECR_REGISTRY"/cloudsbits-audiotube-sandbox:gateway-"$IMAGE_TAG"
        
      - name: Build and push notification service Docker image
        id: build-notification
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t "$ECR_REGISTRY"/cloudsbits-audiotube-sandbox:notification-"$IMAGE_TAG" -f src/notification/Dockerfile src/notification
          docker push "$ECR_REGISTRY"/cloudsbits-audiotube-sandbox:notification-"$IMAGE_TAG"
